### ISSUE TITLE
where were they from to views and locations?  were they from f"{prefix}_images.npy"?

### ISSUE THREAD

**Issue by eeric** [facebookresearch/VICRegL#12]
(val_view, (views, locations)), labels = inputs

**Comment by eeric** [comment]
https://github.com/facebookresearch/VICRegL/blob/main/transforms.py
the 333th line

**Comment by Adrien987k** [comment]
Hi, the views are the transformed images, loaded from ImageNet, and the locations are the coordinates maps of the crops which are generated by the `_location_to_NxN_grid` function from the crop parameters randomly sampled in the `RandomResizedCropWithLocation` class.

The train_images.npy and val_images.npy are just ImageNet stored in numpy tensor files.
