### ISSUE TITLE
Symmetry on local and feature-based loss functions

### ISSUE THREAD

**Issue by ME220397** [facebookresearch/VICRegL#6]
Hello, 

Thank you for your work! 

I'm raising an issue because, in your paper, it is said that both location and feature-based loss functions are symmetrized (Equation 4). But it seems to be different on the code.

I think a + sign is missing in the local_loss function of the class VICRegL. In the local_loss function, you're not updating but overwriting the inv, var and cov loss. Then you divide them by the number of iterations.

![image](https://user-images.githubusercontent.com/44203923/202867117-2f8d3eb2-5b6c-4efa-a92b-e5d67419b87e.png)

Best regards,
Elias.

**Comment by Adrien987k** [comment]
Hi,

Thanks for your comment as this is a real issue.
The numbers in the paper were obtained with an internal codebase that does not have this issue.

We are currently investigating if that makes a big difference but we will update the code and fix the issue soon.

**Comment by Adrien987k** [comment]
Hi,

We have updated the code and the issue is fixed.

Thanks again for reporting it.
