### ISSUE TITLE
No 'InterpolationMode' in torchvision 0.8.2

### ISSUE THREAD

**Issue by hugoych** [facebookresearch/VICRegL#7]
Hi, 
See the previous issue from the vicreg repo (https://github.com/facebookresearch/vicreg/issues/19). 

If I'm correct, `torchvision.transforms.InterpolationMode` has only been introduced in 0.9.0 version. Thus, the requirement mentioned in the README of `torchvision>=0.8.2` can lead to an ImportError.

**Comment by ds2268** [comment]
I have tested it one the latest PyTorch and it works, with a small modification - https://github.com/facebookresearch/VICRegL/pull/8.

**Comment by Adrien987k** [comment]
Hi,

Thanks for pointing this out! The correct pytorch version is actually 1.8.1 and torchvision is 0.9.1.
I have updated the readme.
